version: "3.1"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: sqlserver2019_DB
  enviroment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: YOUR_SA_PASSWORD
  volumes:
    - ~/docker/sqlserver-data:/var/opt/mssql
  ports:
    - "1433:1433"
